#!/bin/bash
# User provisioning. Runs as the guest user on every boot; everything here must be idempotent.
set -eux -o pipefail

export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"

# --- shell ----------------------------------------------------------------------
mkdir -p "$HOME/.config/fish"
cat > "$HOME/.config/fish/config.fish" <<'EOF'
# Generated by lima-sandbox provisioning; edits are overwritten on boot.
set -g fish_greeting
set -gx EDITOR vim
# ~/.local/bin first, so its cargo wrapper wins over the rustup proxy in ~/.cargo/bin.
fish_add_path --global --move "$HOME/.local/bin" "$HOME/.cargo/bin"
EOF

# --- jj identity ------------------------------------------------------------------
mkdir -p "$HOME/.config/jj"
cat > "$HOME/.config/jj/config.toml" <<'EOF'
# Generated by lima-sandbox provisioning; edits are overwritten on boot.
[user]
name = "Patrick Schultz"
email = "pschultz@broadinstitute.org"

[ui]
paginate = "never"
EOF

git config --global user.name "Patrick Schultz"
git config --global user.email "pschultz@broadinstitute.org"

# GitHub auth: per-owner tokens from `gh-token add <owner>`. git asks the sandbox credential
# helper, which needs the repo path to pick the owner; the gh wrapper does the same for gh.
mkdir -p "$HOME/.config/gh-tokens"; chmod 700 "$HOME/.config/gh-tokens"
git config --global credential.helper sandbox
git config --global credential.useHttpPath true

# Global ignore rules, mirrored from the host's ~/.config/git/ignore. jj snapshots the working
# copy on every command, so without these the guest would track .DS_Store and friends.
mkdir -p "$HOME/.config/git"
cat > "$HOME/.config/git/ignore" <<'EOF'
.DS_Store
.ensime
.ensime_cache/
.ipynb_checkpoints/
**/.claude/settings.local.json
EOF

# --- rust -------------------------------------------------------------------------
if [ ! -x "$HOME/.cargo/bin/rustup" ]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y --no-modify-path --default-toolchain nightly --profile default
fi
for tc in nightly stable; do
  rustup toolchain list | grep -q "^$tc-" || rustup toolchain install "$tc" --profile default
  rustup target list --toolchain "$tc" --installed | grep -qx x86_64-unknown-linux-gnu \
    || rustup target add x86_64-unknown-linux-gnu --toolchain "$tc"
  rustup component list --toolchain "$tc" --installed | grep -q '^rust-analyzer' \
    || rustup component add rust-analyzer --toolchain "$tc"
done

# Target dirs: the cargo wrapper gives each workspace its own dir on /mnt/lima-cargo, so nothing
# here sets target-dir. Builds never land in target/ on a mount, where host builds live.
mkdir -p "$HOME/.local/bin"
ln -sfn /usr/local/bin/sandbox-cargo "$HOME/.local/bin/cargo"
sandbox-gc-targets

# kache caches rustc outputs across workspaces, so a fresh workspace's target dir fills from hits.
# Pinned: releases are frequent, and a reboot should not pull in a new one. Bump both together.
KACHE_VERSION="1.0.0"
KACHE_SHA256="88abd848be7d300d4e30b8510ebdc45990dae3f96b6591e3498209639cf34701"
if [ "$("$HOME/.local/bin/kache" --version 2>/dev/null | awk '{print $2}')" != "$KACHE_VERSION" ]; then
  tmp=$(mktemp -d)
  curl -fsSL -o "$tmp/kache.tar.gz" \
    "https://github.com/kunobi-ninja/kache/releases/download/v${KACHE_VERSION}/kache-aarch64-unknown-linux-musl.tar.gz"
  echo "$KACHE_SHA256  $tmp/kache.tar.gz" | sha256sum -c -
  tar -xzf "$tmp/kache.tar.gz" -C "$tmp" kache
  install -m 0755 "$tmp/kache" "$HOME/.local/bin/kache"
  rm -rf "$tmp"
fi

# The store shares the XFS disk with the target dirs, so restores are reflink clones. The daemon's
# defaults stay on: removing target dirs of deleted workspaces, the 10 GiB free-space floor, and
# seeding new target dirs with registry units from another checkout.
mkdir -p "$HOME/.config/kache"
cat > "$HOME/.config/kache/config.toml" <<'EOF'
# Generated by lima-sandbox provisioning; edits are overwritten on boot.
[cache]
local_store = "/mnt/lima-cargo/kache"
local_max_size = "60GiB"
# Storing every relinked 700-800 MB test binary made concurrent edit loops slower each round
# (datafusion-sandbox: 45 s to 88 s per build). mold relinks them in about a second instead.
cache_executables = false
EOF
systemctl --user cat kache.service >/dev/null 2>&1 || "$HOME/.local/bin/kache" daemon install

# Unquoted heredoc so $HOME expands: an absolute wrapper path works whatever PATH cargo gets.
cat > "$HOME/.cargo/config.toml" <<EOF
# Generated by lima-sandbox provisioning; edits are overwritten on boot.
[build]
rustc-wrapper = "$HOME/.local/bin/kache"

# Link with mold through the wrappers from system.sh.
[target.aarch64-unknown-linux-gnu]
linker = "cc-mold"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-cc-mold"

# cc-rs and cmake-rs pick these up for C/C++ dependencies when cross compiling.
[env]
CC_x86_64_unknown_linux_gnu = "x86_64-linux-gnu-gcc"
CXX_x86_64_unknown_linux_gnu = "x86_64-linux-gnu-g++"
AR_x86_64_unknown_linux_gnu = "x86_64-linux-gnu-ar"
EOF

# cargo-binstall fetches prebuilt release binaries into ~/.cargo/bin. It is https-only by default
# and verifies signatures when the crate publishes them; the old --secure flag is a no-op.
command -v cargo-binstall >/dev/null || curl -L --proto '=https' --tlsv1.2 -sSf \
  https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
command -v cargo-nextest >/dev/null || cargo binstall cargo-nextest --no-confirm

# --- uv, claude ----------------------------------------------------------------------
command -v uv >/dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh
command -v claude >/dev/null || curl -fsSL https://claude.ai/install.sh | bash

# --- humanlayer daemon -----------------------------------------------------------------
# User-level npm globals go to ~/.local. The system prefix /usr is root-owned, and the daemon
# self-updates with `npm install -g` as this user. Root's globals (codex, pyright) stay in /usr.
npm config set prefix "$HOME/.local"
command -v humanlayer >/dev/null || npm install -g @humanlayer/cli@latest

# Runs on the stored login from `humanlayer login`, not a launch token: launch tokens expire
# within a day, and the daemon disables self-update for them under systemd. It self-updates by
# exiting 75 for systemd to restart it. Without a login the condition fails and nothing starts.
# PATH matches the fish config, so sessions get the cargo wrapper, claude and the gh wrapper.
mkdir -p "$HOME/.config/systemd/user"
cat > "$HOME/.config/systemd/user/humanlayer-daemon.service" <<'EOF'
# Generated by lima-sandbox provisioning; edits are overwritten on boot.
[Unit]
Description=HumanLayer daemon
After=network-online.target
ConditionPathExists=%h/.humanlayer/riptide/workos-session-prod.json

[Service]
Type=simple
WorkingDirectory=%h
Environment=PATH=%h/.local/bin:%h/.cargo/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=%h/.local/bin/humanlayer daemon launch
Restart=always
RestartSec=5s

[Install]
WantedBy=default.target
EOF
systemctl --user daemon-reload
systemctl --user enable --now humanlayer-daemon.service

# --- agent config ---------------------------------------------------------------------
# Symlinks into the read-only ~/.agents mount are created here, once. Generated files
# (settings, instructions, codex config, codex skill links) come from sandbox-sync.
mkdir -p "$HOME/.claude" "$HOME/.codex/skills" "$HOME/.claude/worktrees"
ln -sfn ../.agents/skills "$HOME/.claude/skills"
ln -sfn ../.agents/claude/scripts "$HOME/.claude/scripts"

sandbox-sync
