#!/bin/bash
# User provisioning. Runs as the guest user on every boot; everything here must be idempotent.
set -eux -o pipefail

export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"

# --- shell ----------------------------------------------------------------------
mkdir -p "$HOME/.config/fish"
cat > "$HOME/.config/fish/config.fish" <<'EOF'
# Generated by lima-sandbox provisioning; edits are overwritten on boot.
set -g fish_greeting
set -gx EDITOR vim
fish_add_path --global "$HOME/.cargo/bin" "$HOME/.local/bin"
EOF

# --- jj identity ------------------------------------------------------------------
mkdir -p "$HOME/.config/jj"
cat > "$HOME/.config/jj/config.toml" <<'EOF'
# Generated by lima-sandbox provisioning; edits are overwritten on boot.
[user]
name = "Patrick Schultz"
email = "pschultz@broadinstitute.org"

[ui]
paginate = "never"
EOF

git config --global user.name "Patrick Schultz"
git config --global user.email "pschultz@broadinstitute.org"

# GitHub auth: per-owner tokens from `gh-token add <owner>`. git asks the sandbox credential
# helper, which needs the repo path to pick the owner; the gh wrapper does the same for gh.
mkdir -p "$HOME/.config/gh-tokens"; chmod 700 "$HOME/.config/gh-tokens"
git config --global credential.helper sandbox
git config --global credential.useHttpPath true

# Global ignore rules, mirrored from the host's ~/.config/git/ignore. jj snapshots the working
# copy on every command, so without these the guest would track .DS_Store and friends.
mkdir -p "$HOME/.config/git"
cat > "$HOME/.config/git/ignore" <<'EOF'
.DS_Store
.ensime
.ensime_cache/
.ipynb_checkpoints/
**/.claude/settings.local.json
EOF

# --- rust -------------------------------------------------------------------------
if [ ! -x "$HOME/.cargo/bin/rustup" ]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y --no-modify-path --default-toolchain nightly --profile default
fi
for tc in nightly stable; do
  rustup toolchain list | grep -q "^$tc-" || rustup toolchain install "$tc" --profile default
  rustup target list --toolchain "$tc" --installed | grep -qx x86_64-unknown-linux-gnu \
    || rustup target add x86_64-unknown-linux-gnu --toolchain "$tc"
  rustup component list --toolchain "$tc" --installed | grep -q '^rust-analyzer' \
    || rustup component add rust-analyzer --toolchain "$tc"
done

# One shared target dir on the VM disk: fast, and it does not collide with host builds.
# Cargo resolves relative config paths against the parent of the .cargo dir, i.e. $HOME.
mkdir -p "$HOME/.cargo-target"
cat > "$HOME/.cargo/config.toml" <<'EOF'
# Generated by lima-sandbox provisioning; edits are overwritten on boot.
[build]
target-dir = ".cargo-target"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

# cc-rs and cmake-rs pick these up for C/C++ dependencies when cross compiling.
[env]
CC_x86_64_unknown_linux_gnu = "x86_64-linux-gnu-gcc"
CXX_x86_64_unknown_linux_gnu = "x86_64-linux-gnu-g++"
AR_x86_64_unknown_linux_gnu = "x86_64-linux-gnu-ar"
EOF

# --- uv, claude ----------------------------------------------------------------------
command -v uv >/dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh
command -v claude >/dev/null || curl -fsSL https://claude.ai/install.sh | bash

# --- agent config ---------------------------------------------------------------------
# Symlinks into the read-only ~/.agents mount are created here, once. Generated files
# (settings, instructions, codex config, codex skill links) come from sandbox-sync.
mkdir -p "$HOME/.claude" "$HOME/.codex/skills" "$HOME/.claude/worktrees"
ln -sfn ../.agents/skills "$HOME/.claude/skills"
ln -sfn ../.agents/claude/scripts "$HOME/.claude/scripts"

sandbox-sync
